"""create_analytics_tables

Revision ID: 7832c636fe7a
Revises: c81e04b22196
Create Date: 2026-03-09 14:25:22.597862

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7832c636fe7a'
down_revision: Union[str, None] = 'c81e04b22196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey_progress_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('chapter_progress', sa.JSON(), nullable=True),
    sa.Column('total_activities_completed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(
        ['journey_id'], ['journeys.id'],
        name=op.f('fk_journey_progress_snapshots_journey_id_journeys'),
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journey_progress_snapshots')),
    sa.UniqueConstraint('user_id', 'journey_id', 'snapshot_date', name='uq_snapshot_user_journey_date')
    )
    with op.batch_alter_table('journey_progress_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journey_progress_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('attribution_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('app_open_timestamp', sa.DateTime(), nullable=False),
    sa.Column('attribution_window_hours', sa.Integer(), nullable=False),
    sa.Column('activities_completed_after', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(
        ['notification_id'], ['notifications.id'],
        name=op.f('fk_attribution_events_notification_id_notifications'),
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribution_events'))
    )
    with op.batch_alter_table('attribution_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attribution_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_attribution_user_notif', ['user_id', 'notification_id'], unique=False)

    # ### end Alembic commands ###

    # Create materialized view for segment performance
    op.execute("""
        CREATE MATERIALIZED VIEW IF NOT EXISTS segment_performance AS
        SELECT
            n.state_at_generation AS user_state,
            up.learning_reason,
            up.proficiency_level,
            n.theme,
            n.mode,
            COUNT(n.id) AS total_sent,
            COUNT(ne_opened.id) AS total_opened,
            COUNT(ae.id) AS total_attributed_returns,
            AVG(ae.activities_completed_after)
                AS avg_post_return_activities,
            ROUND(
                COUNT(ne_opened.id)::numeric
                / NULLIF(COUNT(n.id), 0) * 100, 2
            ) AS open_rate_pct
        FROM notifications n
        LEFT JOIN user_profiles up
            ON n.user_id = up.user_id
        LEFT JOIN notification_events ne_opened
            ON n.id = ne_opened.notification_id
            AND ne_opened.event_type = 'opened'
        LEFT JOIN attribution_events ae
            ON n.id = ae.notification_id
        GROUP BY
            n.state_at_generation,
            up.learning_reason,
            up.proficiency_level,
            n.theme,
            n.mode
    """)
    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS
            ix_segment_perf_composite
        ON segment_performance (
            user_state, learning_reason,
            proficiency_level, theme, mode
        )
    """)


def downgrade() -> None:
    op.execute("DROP MATERIALIZED VIEW IF EXISTS segment_performance")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attribution_events', schema=None) as batch_op:
        batch_op.drop_index('ix_attribution_user_notif')
        batch_op.drop_index(batch_op.f('ix_attribution_events_user_id'))

    op.drop_table('attribution_events')
    with op.batch_alter_table('journey_progress_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journey_progress_snapshots_user_id'))

    op.drop_table('journey_progress_snapshots')
    # ### end Alembic commands ###
