"""create_notification_tables

Revision ID: c81e04b22196
Revises: e104892b7717
Create Date: 2026-03-09 14:14:56.548735

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c81e04b22196'
down_revision: Union[str, None] = 'e104892b7717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('state_at_generation', sa.String(length=50), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cta', sa.String(length=255), nullable=False),
    sa.Column('generation_method', sa.String(length=30), nullable=False),
    sa.Column('llm_prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('clevertap_campaign_id', sa.String(length=100), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_notifications_journey_id_journeys')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_mode_created', ['mode', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_scheduled', ['user_id', 'scheduled_for'], unique=False)

    op.create_table('notification_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(
        ['notification_id'], ['notifications.id'],
        name=op.f('fk_notification_events_notification_id_notifications'),
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_events'))
    )
    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.create_index('ix_notif_events_notif_type', ['notification_id', 'event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_events_notification_id'), ['notification_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_events_notification_id'))
        batch_op.drop_index('ix_notif_events_notif_type')

    op.drop_table('notification_events')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_scheduled')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index('ix_notifications_mode_created')

    op.drop_table('notifications')
    # ### end Alembic commands ###
