"""create_user_and_config_tables

Revision ID: e104892b7717
Revises: f16ca886f985
Create Date: 2026-03-09 14:00:58.815971

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e104892b7717'
down_revision: Union[str, None] = 'f16ca886f985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_config'))
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('learning_reason', sa.String(length=100), nullable=True),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('proficiency_level', sa.String(length=10), nullable=True),
    sa.Column('language_comfort', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles'))
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('user_journey_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('current_state', sa.String(length=50), nullable=False),
    sa.Column('state_entered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('current_chapter_id', sa.Uuid(), nullable=True),
    sa.Column('current_quest_id', sa.Uuid(), nullable=True),
    sa.Column('activities_completed', sa.Integer(), nullable=False),
    sa.Column('chapter_progress', sa.JSON(), nullable=True),
    sa.Column('retry_count_window', sa.Integer(), nullable=False),
    sa.Column('avg_score_window', sa.Float(), nullable=False),
    sa.Column('avg_completion_speed', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(
        ['current_chapter_id'], ['chapters.id'],
        name=op.f('fk_user_journey_state_current_chapter_id_chapters'),
    ),
    sa.ForeignKeyConstraint(
        ['current_quest_id'], ['quests.id'],
        name=op.f('fk_user_journey_state_current_quest_id_quests'),
    ),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_user_journey_state_journey_id_journeys')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_journey_state')),
    sa.UniqueConstraint('user_id', 'journey_id', name='uq_user_journey')
    )
    with op.batch_alter_table('user_journey_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_journey_state_journey_id'), ['journey_id'], unique=False)
        batch_op.create_index('ix_user_journey_state_last_activity', ['last_activity_at'], unique=False)
        batch_op.create_index('ix_user_journey_state_state', ['current_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_journey_state_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_journey_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_journey_state_user_id'))
        batch_op.drop_index('ix_user_journey_state_state')
        batch_op.drop_index('ix_user_journey_state_last_activity')
        batch_op.drop_index(batch_op.f('ix_user_journey_state_journey_id'))

    op.drop_table('user_journey_state')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))

    op.drop_table('user_profiles')
    op.drop_table('app_config')
    # ### end Alembic commands ###
