"""create_journey_hierarchy_tables

Revision ID: f16ca886f985
Revises:
Create Date: 2026-03-09 13:50:42.324134

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f16ca886f985'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journeys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_chapters', sa.Integer(), nullable=False),
    sa.Column('llm_journey_summary', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journeys'))
    )
    op.create_table('chapters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=True),
    sa.Column('llm_analysis', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_chapters_journey_id_journeys')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters'))
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index('ix_chapters_journey_chapter', ['journey_id', 'chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapters_journey_id'), ['journey_id'], unique=False)

    op.create_table('quests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('chapter_id', sa.Uuid(), nullable=False),
    sa.Column('quest_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_quests_chapter_id_chapters')),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_quests_journey_id_journeys')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quests'))
    )
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quests_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quests_journey_id'), ['journey_id'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('quest_id', sa.Uuid(), nullable=False),
    sa.Column('activity_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_activities_journey_id_journeys')),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], name=op.f('fk_activities_quest_id_quests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_journey_id'), ['journey_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_quest_id'), ['quest_id'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_lessons_activity_id_activities')),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_lessons_journey_id_journeys')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_journey_id'), ['journey_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('task_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_tasks_journey_id_journeys')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_tasks_lesson_id_lessons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_journey_id'), ['journey_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_lesson_id'), ['lesson_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_journey_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_journey_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_activity_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_quest_id'))
        batch_op.drop_index(batch_op.f('ix_activities_journey_id'))

    op.drop_table('activities')
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quests_journey_id'))
        batch_op.drop_index(batch_op.f('ix_quests_chapter_id'))

    op.drop_table('quests')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_journey_id'))
        batch_op.drop_index('ix_chapters_journey_chapter')

    op.drop_table('chapters')
    op.drop_table('journeys')
    # ### end Alembic commands ###
